#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: system
#    password: Knowledge_1
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa   
  jpa:
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.Oracle10gDialect
    #database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: create-drop    
      show-sql: true
server:
  port: 8080
  